# Generated by Django 5.0.6 on 2024-07-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('pk',), 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='another_invite_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Мой инвайт-код'),
        ),
        migrations.AddField(
            model_name='user',
            name='my_invite_code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True, verbose_name='Мой инвайт-код'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=1, max_length=12, unique=True, verbose_name='Телефон'),
            preserve_default=False,
        ),
    ]
