# Generated by Django 5.0.6 on 2024-07-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_remove_user_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='another_invite_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Чужой инвайт-код'),
        ),
    ]
