# Generated by Django 5.0.6 on 2024-07-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_another_invite_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tmp_code',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Код верификации'),
        ),
    ]
