# Generated by Django 5.0.6 on 2024-07-17 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_tmp_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tmp_code',
        ),
    ]
